---
- name: Create directory for backend
    file:
      path: /home/ubuntu/backend/
      state: directory

- name: Copy backend files
    copy:
      src: ../../backend/dist
      dest: /home/ubuntu/backend

- name: Start server
    become: true
    command: pm2 start -f ./main.js
    args:
      chdir: /home/ubuntu/backend/dist