version: 2.1


executors:
  node:
    docker:
      - image: circleci/node:13.8.0

commands:
  install-dep:
    parameters:
      path:
        type: string
    steps:
      - run:
          name: npm install
          working_directory: ./<< parameters.path >>
          command: npm install
      - persist_to_workspace:
          root: .
          paths:
            - << parameters.path >>/node_modules

  build:
    parameters:
      path:
        type: string
    steps:
      - attach_workspace:
          at: .
      - run:
          name: build << parameters.path >>
          working_directory: ./<< parameters.path >>
          command: npm run build

jobs:
  install-backend-dep:
    executor: node
    steps:
      - checkout
      - install-dep:
          path: backend

  install-frontend-dep:
    executor: node
    steps:
      - checkout
      - install-dep:
          path: frontend

  build-backend:
    executor: node
    steps:
      - checkout
      - build:
          path: backend

  build-frontend:
    executor: node
    steps:
      - checkout
      - build:
          path: frontend

workflows:
  default:
    jobs:
      - install-backend-dep
      - install-frontend-dep

      - build-backend:
          requires:
            - install-backend-dep

      - build-frontend:
          requires:
            - install-frontend-dep            