version: 2.1


executors:
  node:
    docker:
      - image: circleci/node:13.8.0

commands:
  install-dep:
    parameters:
      path:
        type: string
    steps:
      - restore_cache:
          keys:
            - npm-modules-cache-{{ checksum "./<< parameters.path >>/package-lock.json" }}
      - run:
          name: npm install
          working_directory: ./<< parameters.path >>
          command: npm install
      - save_cache:
          key: npm-modules-cache-{{ checksum "./<< parameters.path >>/package-lock.json" }}
          paths:
            - ./<< parameters.path >>/nodes_modules



  build:
    parameters:
      path:
        type: string
    steps:
      - restore_cache:
          keys:
            - npm-modules-cache-{{ checksum "./<< parameters.path >>/package-lock.json" }}
      - run:
          name: build << parameters.path >>
          working_directory: ./<< parameters.path >>
          command: npm run build

  test:
    parameters:
      path:
        type: string
    steps:
      - restore_cache:
          keys:
            - npm-modules-cache-{{ checksum "./<< parameters.path >>/package-lock.json" }}
      - run:
          name: test << parameters.path >>
          working_directory: ./<< parameters.path >>
          command: npm run test          

jobs:
  install-backend-dep:
    executor: node
    steps:
      - checkout
      - install-dep:
          path: backend

  install-frontend-dep:
    executor: node
    steps:
      - checkout
      - install-dep:
          path: frontend

  build-backend:
    executor: node
    steps:
      - checkout
      - build:
          path: backend

  build-frontend:
    executor: node
    steps:
      - checkout
      - build:
          path: frontend

  test-backend:
    executor: node
    steps:
      - checkout
      - test:
          path: backend

  test-frontend:
    executor: node
    steps:
      - checkout
      - test:
          path: frontend          

workflows:
  default:
    jobs:
      - install-backend-dep
      - install-frontend-dep

      - build-backend:
          requires:
            - install-backend-dep

      - build-frontend:
          requires:
            - install-frontend-dep

      - test-backend:
          requires:
            - build-backend

      - test-frontend:
          requires:
            - build-frontend                      